name: sha2

on:
  pull_request:
    paths:
      - "sha2/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: sha2

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  # Linux tests
  linux:
    strategy:
      matrix:
        include:
          # 32-bit Linux/x86
          - target: i686-unknown-linux-gnu
            rust: 1.43.0 # MSRV
            deps: sudo apt install gcc-multilib
          - target: i686-unknown-linux-gnu
            rust: stable
            deps: sudo apt install gcc-multilib

          # 64-bit Linux/x86_64
          - target: x86_64-unknown-linux-gnu
            rust: 1.43.0 # MSRV
            deps: true
          - target: x86_64-unknown-linux-gnu
            rust: stable
            deps: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ${{ matrix.deps }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo test --target ${{ matrix.target }} --release

  # Windows tests
  windows:
    strategy:
      matrix:
        include:
          # 64-bit Windows (GNU)
          - target: x86_64-pc-windows-gnu
            toolchain: 1.43.0 # MSRV
          - target: x86_64-pc-windows-gnu
            toolchain: stable

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo test --target ${{ matrix.target }} --release

  # Cross-compiled tests
  cross:
    strategy:
      matrix:
        include:
          # ARM64
          - target: aarch64-unknown-linux-gnu
            rust: 1.43.0 # MSRV
          - target: aarch64-unknown-linux-gnu
            rust: stable

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ${{ matrix.deps }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo install cross
      - run: cross test --target ${{ matrix.target }} --release
