name: whirlpool

on:
  pull_request:
    paths:
      - "whirlpool/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: whirlpool

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"
  # Workaround for: https://github.com/rust-lang/cargo/issues/10303
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  # Linux tests
  linux:
    strategy:
      matrix:
        include:
          # 32-bit Linux/x86
          - target: i686-unknown-linux-gnu
            toolchain: 1.45.0 # MSRV
            deps: sudo apt update && sudo apt install gcc-multilib
          - target: i686-unknown-linux-gnu
            toolchain: stable
            deps: sudo apt update && sudo apt install gcc-multilib

          # 64-bit Linux/x86_64
          - target: x86_64-unknown-linux-gnu
            toolchain: 1.45.0 # MSRV
            deps: true
          - target: x86_64-unknown-linux-gnu
            toolchain: stable
            deps: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
      - run: ${{ matrix.deps }}
      - run: cargo test --target ${{ matrix.target }} --release

  # macOS tests
  macos:
    strategy:
      matrix:
        toolchain:
          - 1.54.0 # MSRV
          - stable

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: x86_64-apple-darwin
      - run: cargo test --release
